exporter_port: $EXPORTER_PORT|9091 # the port that exposes cost metrics
polling_interval_seconds: $POLLING_INTERVAL_SECONDS|28800 # the interval in seconds between each cost polling
log_level: $LOG_LEVEL|INFO # the log level

dd_api_key: $DD_API_KEY # the Datadog API key
dd_app_key: $DD_APP_KEY # the Datadog APPLICATION key
dd_host: $DD_HOST|datadoghq.eu # the host of the Datadog API
dd_debug: $DD_DEBUG|False # enable debug mode
